[package]
name = "margined_utils"
version = "0.1.0"
authors = ["Margined Protocol"]
edition = "2018"
description = "Common helpers for margin protocol contracts"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = { version = "0.13.2" }
cw20-base = { version = "0.13.2", features = ["library"] }
cw-multi-test = "0.13.2"
cosmwasm-std = { version = "1.0.0" }
cosmwasm-storage = { version = "1.0.0" }
margined_common = { version = "0.1.0", path = "../margined_common"}
margined_perp = { version = "0.1.0", path = "../margined_perp"}
margined_vamm = { version = "0.1.0", path = "../../contracts/margined_vamm" }
margined_engine = { version = "0.1.0", path = "../../contracts/margined_engine" }
margined_fee_pool = { version = "0.1.0", path = "../../contracts/margined_fee_pool" }
margined_insurance_fund = { version = "0.1.0", path = "../../contracts/margined_insurance_fund" }
margined_pricefeed = { version = "0.1.0", path = "../../contracts/margined_pricefeed" }
mock_pricefeed = { version = "0.1.0", path = "../../contracts/mocks/mock_pricefeed" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
serde_json = "^1.0"

[profile.release]
overflow-checks = true